export const INVENTORY_VOICE_SCHEMA = {
  page: 'inventory',
  entityType: 'medication',
  allowedIntents: [
    'search_medication',
    'filter_expired',
    'clear_expired_filter',
    'open_add_medication',
    'paginate',
    'filter_by_status',
    'navigate',
  ],
  controls: ['searchInput', 'statusFilter', 'expiryFilter', 'categoryFilter', 'expiredToggle', 'addMedicationButton', 'pagination'],
  actions: [
    'INVENTORY_OPEN_ADD',
    'INVENTORY_SHOW_EXPIRED',
    'INVENTORY_CLEAR_EXPIRED',
    'INVENTORY_CLEAR_SEARCH',
    'INVENTORY_NEXT_PAGE',
    'INVENTORY_PREV_PAGE',
    'INVENTORY_FILTER_LOW_STOCK',
    'INVENTORY_FILTER_EXPIRING',
    'INVENTORY_FILTER_EXPIRED_STATUS',
    'INVENTORY_FILTER_OUT_OF_STOCK',
    'INVENTORY_FILTER_IN_STOCK',
    'INVENTORY_SEARCH',
    'NAVIGATE',
  ],
};
